databases:
  - name: VipX
    databaseName: VipX
    user: VipX

services:
  - type: web
    plan: free
    name: VipX
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m VipX
    repo: https://github.com/asaaqa/VIP-MUSIC
    branch: master 
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_DB_URI 
        sync: false
      - key: LOG_GROUP_ID 
        sync: false
      - key: OWNER_ID
        sync: false    
    autoDeploy: false
